manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: w84miracle
      url-base: https://github.com/w84miracle
    - name: krikun98
      url-base: https://github.com/krikun98
  projects:
    - name: zmk
      remote: krikun98
      revision: 5430fb009f81787c4afaa0829e302cbadae2a86a
      import: app/west.yml
  self:
    path: config
