manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: w84miracle
      url-base: https://github.com/w84miracle
    - name: krikun98
      url-base: https://github.com/krikun98
  projects:
    - name: zmk
      remote: krikun98
      revision: 9da081c8af5717c8d968443b735301923ac4c7a8
      import: app/west.yml
  self:
    path: config
