manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: w84miracle
      url-base: https://github.com/w84miracle
  projects:
    - name: zmk
      remote: w84miracle
      revision: mousekeys
      import: app/west.yml
  self:
    path: config
